### ISSUE TITLE
#Proxy tab show errors with PASS policy in proxy groups

### ISSUE THREAD

**Issue by bash99** [MetaCubeX/Dashboard#4]
when use meta's new feature
https://clashmeta.gitbook.io/meta/%20function/proxygroups/pass
``` yaml
proxy-groups:
  - name: NoAD
    type: select
    proxies:
      - PASS
      - REJECT
```

the #proxy tab crashed, other tab is fine.
